### ISSUE TITLE
pytaglib should support reading data that is in memory

### ISSUE THREAD

**Issue by seifertm** [supermihi/pytaglib#17]
Currently, the only way to analyse audio data is to point pytaglib to the file where the data is stored by passing the file path to `taglib.File`. In the use case I am having, the data that should be analysed is no longer available as a file and was already loaded from the disk into memory. Unfortunately, the current API of pytaglib does not seem to support reading data that is not contained in a file.

It is possible to work around this by creating a temporary directory, writing the original data to a file, and finally do the analysis from the copied file. Note that directly writing to temporary file and passing the path to the temp file to `taglib.File` results in an `OSError`.

As you can see, this is a tedious workaround and it would be nice to be able to pass a binary string for example. Is this possible in theory?

**Comment by supermihi** [comment]
Hi, thanks for your report. The basic policy of pytaglib is not to add any functionality that's not included in taglib itself, because I intend to keep this package a very lightweight wrapper.

However! [Taglib-1.11BETA](https://github.com/taglib/taglib/releases/tag/v1.11beta) supports creating a `FileRef` object from an `IOStream`. I'll evaluate the possibilities to include this feature in pytaglib ASAP. Then, creating a stream from your bytevector should be straightforward.

**Comment by supermihi** [comment]
Hi @seifertm,
sorry for my late reply. Unfortunatelly, there's a serious problem when reading from memory instead of reading from a file: The current implementation uses `FileRef::create()` to create a file, which in turn guesses the file type from its file extension, because taglib does not have built-in MIME type resolver to automatically determine the type from the actual content (like e.g. the unix `file` command).

As this is obviously not possible when reading a stream, I would have to implemetd the type resolving in `pytaglib`. While that itself should be rather simple (at least, on unix) using `libmagic`, it would also require to include **all** `taglib::File` implementations in `pytaglib̀ , which is something I definitely want to avoid.

Hence, for the moment I'm afraid I have to close this as *wontfix*. If future taglib versions offer a simpler way of file type resolving, we might be able to re-think on this.

Michael

**Comment by seifertm** [comment]
I am not that familiar with taglib, but I think I understand the problem here.

Thanks for your efforts and the detailed explanation!

- Michael
