### ISSUE TITLE
Update Windows wheel with TagLib 1.11 Release

### ISSUE THREAD

**Issue by hiccup7** [supermihi/pytaglib#20]
pytaglib is really great.  I tried pytaglib v1.2.0 of the Windows wheel on WAV files, and it worked very well.  Thanks for creating this package!

When I looked at the release notes on http://taglib.github.io/ for TagLib 1.11 Release - April 29, 2016, I became concerned about the many file corruption bugs that were fixed after the pytaglib v1.2.0 release.  Please update the Windows wheel with the TagLib 1.11 Release.

Does TagLib 1.11 require other changes in pytaglib?

**Comment by supermihi** [comment]
Thanks for your report. I'll make an updated wheel as soon as I find some spare time. Taglib 1.11 should not require any changes to pytaglib itself because it's completely API compatible with previous versions.

**Comment by hiccup7** [comment]
I see that pytaglib v1.2.1 was released, but I don't see it documented at https://github.com/supermihi/pytaglib/blob/master/NEWS
Does the wheel at pypi include TagLib 1.11 Release?

**Comment by supermihi** [comment]
Sorry, I forgot to push the master branch – will catch up later today. Yes, the 1.2.1 Windows wheel includes Taglib 1.11 (in fact, that's the only change of this release). The PyPI page is already updated:
https://pypi.python.org/pypi/pytaglib/1.2.1

**Comment by hiccup7** [comment]
@supermihi - I downloaded pytaglib v1.2.1 from PyPI, and it is working well.  Thanks!

Does pytaglib provide a method to query the TagLib version installed?

**Comment by supermihi** [comment]
No, for technical reasons: Taglib exposes its version information through static preprocessor defines in taglib.h. I can read that information with pytaglib, however the pytaglib module then will contain the version number _at the time pytaglib was compiled_. If you update your system's taglib version (to which the pytaglib module is usually dynamically bound), it would wrongly continue to report to older, compile-time version. (The windows wheel would technically not be impacted by this issue because it contains a statically built copy of taglib, but then that's a special case and for the sake of cross-platform compatibility the feature set of pytaglib should not depend on the platform or binding mode).

**Comment by supermihi** [comment]
Update: This will probably work when taglib2 is released – see https://github.com/taglib/taglib/pull/748!
