### ISSUE TITLE
RuntimeWarning: applyID3v2Hack parameter is obsolete and will be ignored

### ISSUE THREAD

**Issue by AdrienPensart** [supermihi/pytaglib#22]
I updated taglib to 1.11 and pytaglib to 1.3.0 and recompiled everything, but now I have an error when I create an instance of taglib.File(path), argument applyID3v2Hack should be False by default but the exception is still raised...I don't understand why...

Could you "throw an eye" at this problem ?

**Comment by AdrienPensart** [comment]
Nevermind, I deleted inheritance of my class from your File class and problem is now fixed.

**Comment by supermihi** [comment]
Glad you were able to resolve the issue. I removed the "ID3v2 Hack" in 1.3.0 because it was somewhat ugly and applied only to taglib versions prior to 1.9 which should be rare nowadays.

I've never thought about the implications of inheriting from `taglib.File`, though. How is that related to the hack parameter?

**Comment by AdrienPensart** [comment]
I was just not calling super() in my __init__...so somewhat this hack parameter was True by default elsewhere, I just didn't lose time to find it.

But nah, composition is far better than inheritance in my case.
